server:
  port: 8808
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.67.97:5432/msdb_kjk?
    username: msdb_kjk
    password: szN5$weQ2CiM
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log4j.xml



