server:
  port: 8808
spring:
  datasource:
    db1:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://172.16.67.97:5432/msdb_kjk?
      username: msdb_kjk
      password: szN5$weQ2CiM
    db2:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres?
      username: postgres
      password: 63447285
mybatis:
    mapper-locations: classpath:mapper/*.xml
logging:
    config: classpath:log4j.xml



